# Generated by Django 3.1.6 on 2021-02-11 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='level',
        ),
        migrations.AlterField(
            model_name='owner',
            name='total_data',
            field=models.BigIntegerField(default=0),
        ),
    ]
